# declare global variable
SERVER_PORT: 8888

#port of smtp protocol
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hieu01bdvn@gmail.com
EMAIL_PASSWORD: ocvqndmbczmueyks
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

# server run with port 8080 - default
server:
  port: ${SERVER_PORT}

#config database connection with oracle
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      timeout: 6h
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
    username: testuser
    password: testuser
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          globally_quoted_identifiers: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

paypal:
  client:
    id: demo
    secret: demo
  mode: sandbox
  return-url: http://localhost:8080/user/checkout/paypal/success
  cancel-url: http://localhost:8080/user/checkout/paypal/cancel
jwt:
  signedKey: "demo"

currency:
  api:
    url: "https://v6.exchangerate-api.com/v6/35e55f125051d62ab8e392f6/latest/VND"
